### ISSUE TITLE
[registry-backend] cli setting eventstore.clusterSize=1 fails (for local development purposes)

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-helm-charts#20]
For local development (with just a single node in the Kubernetes cluster: the development laptop) it is required for the eventstore to run as a single container instead of a cluster. This can be applied by setting `clusterSize` to `1` (instead of the default `3`).

BUT this fails in the eventstore helm chart (included and installed with the `.tgz` file in the `registry-backend` chart

Executing the following cli command fails:

```bash
$ helm upgrade --install -n sensrnet-registry registry-backend sensrnet/registry-backend \
     --set eventstore.clusterSize=1 \
     --set mongodb.replicaCount=1
```

with error message:

```bash
Release "registry-backend" does not exist. Installing it now.
Error: template: registry-backend/charts/eventstore/templates/NOTES.txt:12:10: executing "registry-backend/charts/eventstore/templates/NOTES.txt" at <gt .Values.clusterSize 1.0>: error calling gt: incompatible types for comparison
```

**Comment by marcvanandel** [comment]
Quick fix for short term workaround:

1. Clone this (the sensrnet-helm-charts) repo
2. Open the values file `charts/registry-backend/values.yaml` and update `eventstore.clusterSize` from `3` to `1` (and store of cource 😉 )
3. Install this helm chart by referencing this local copy instead of the published version:

```bash
$ sensrnet-helm-charts> helm upgrade --install -n sensrnet-registry registry-backend charts/registry-backend \
     --set eventstore.clusterSize=1 \
     --set mongodb.replicaCount=1
```

**Comment by kad-busses** [comment]
Another alternative is to disable affinity, this way the deployment will still use 3 replica's, but will allow them to all run on the same node
```
helm upgrade -n sensrnet-registry --install registry-backend charts/registry-backend \
  --set eventstore.affinity=null \
  ...
```

We mostly use the standard EventStore Helm Chart. The described problem is actually a problem with the Chart itself https://github.com/EventStore/EventStore.Charts/issues/53. As the chart is deprecated, it will not be fixed. We'll have to consider how best to move forward regarding EventStore and its deployment

**Comment by marcvanandel** [comment]
Oh huh ... too bad they ditched the helm charts ... Do we need to move to another way of working for the EventStore as well then? At least they provided more information and considerations in [this blog post](https://www.eventstore.com/blog/event-store-on-kubernetes) ... in which they advice to install on bare metal 😳 I don't know ... I'm not ready for that, I think 😏

**Comment by kad-busses** [comment]
This is fixed in https://github.com/kadaster-labs/sensrnet-helm-charts/pull/32. We can now use correctly set `eventstore.clusterSize=1`
